#!/usr/bin/env bash
# Generates the skill stubs under .claude/skills from their source under
# project/core/skills.
#
# devkit is its own first consumer, but it does not vendor itself: a copy of a
# skill in this repository would be a second truth next to the original, and the
# copy is the one that runs. So .claude/skills holds stubs instead - the
# frontmatter verbatim, because the `description` is what decides whether a
# skill fires at all, and a pointer at the source for everything else.
#
# Nothing under .claude/skills/<generated> is hand-maintained. Run this after
# changing a skill; .devkit/gates.sh fails when you did not.
#
# Usage:  bash .devkit/stubs.sh [--verify]
#         --verify writes nothing and fails when a stub is stale
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

SKILLS="create-issue implement-feature commit-message"

# devkit-sync is deliberately absent: in this repository it would clone devkit
# into a temp directory and compare the repo against itself. Listing it here
# rather than just leaving it out is what makes --verify able to tell a
# deliberate omission from a skill somebody added upstream and forgot to stub.
EXCLUDED="devkit-sync"
SRC="project/core/skills"
DEST=".claude/skills"
FORGE_RULES="project/forges/github/AGENTS.github.md"

VERIFY=0
case "${1-}" in
  --verify) VERIFY=1 ;;
  "") ;;
  *) echo "usage: stubs.sh [--verify]" >&2; exit 2 ;;
esac

# The block between the first pair of `---` lines, both fences included.
frontmatter() {   # <file>
  awk 'NR == 1 && $0 == "---" { inside = 1; print; next }
       inside && $0 == "---"  { print; exit }
       inside                 { print }' "$1"
}

write_stub() {   # <skill> <destination root>
  local n="$1" dir="$2/$1"
  mkdir -p "${dir}"
  {
    frontmatter "${SRC}/${n}/SKILL.md"
    cat <<EOF

# ${n}

This repository is the devkit itself, so the skill is not vendored here. The
authoritative instructions are in \`${SRC}/${n}/SKILL.md\` — read that file and
follow it.

Where it names a file at the repository root, read it from its pack instead:

| It says | Here it is |
|---|---|
| \`AGENTS.core.md\` | \`project/core/AGENTS.core.md\` |
| \`AGENTS.<forge>.md\` | \`${FORGE_RULES}\` — this repository is on GitHub |

There are no stack packs here, so \`DEVKIT_STACKS\` is empty and no stack rules
apply. The helper scripts next to this file are shims onto the same source
directory; call them by the paths the instructions give.

Generated by \`.devkit/stubs.sh\` — do not edit.
EOF
  } > "${dir}/SKILL.md"
}

write_shims() {   # <skill> <destination root>
  local n="$1" dir="$2/$1" f base
  for f in "${SRC}/${n}"/*.sh; do
    [ -e "${f}" ] || continue
    base="$(basename "${f}")"
    cat > "${dir}/${base}" <<EOF
#!/usr/bin/env bash
# Shim. The real script is ${SRC}/${n}/${base}, which is where it is
# maintained; it resolves the repository root itself, so this adds nothing but
# the path the skill instructions expect.
#
# Generated by .devkit/stubs.sh - do not edit.
exec bash "\$(git rev-parse --show-toplevel)/${SRC}/${n}/${base}" "\$@"
EOF
  done
}

generate() {   # <destination root>
  local n
  for n in ${SKILLS}; do
    write_stub  "${n}" "$1"
    write_shims "${n}" "$1"
  done
}

if [ "${VERIFY}" -eq 1 ]; then
  # A skill that appeared upstream and is neither stubbed nor excluded would
  # simply not exist in this repository, and nothing else would say so.
  unlisted=""
  for d in "${SRC}"/*/; do
    n="$(basename "${d}")"
    case " ${SKILLS} ${EXCLUDED} " in
      *" ${n} "*) ;;
      *) unlisted="${unlisted}${n} " ;;
    esac
  done
  if [ -n "${unlisted}" ]; then
    echo "skills in ${SRC} that are neither stubbed nor excluded: ${unlisted% }"
    echo "add them to SKILLS or to EXCLUDED in .devkit/stubs.sh, then run it"
    exit 1
  fi

  tmp="$(mktemp -d)"
  trap 'rm -rf "${tmp}"' EXIT
  generate "${tmp}"
  stale=""
  for n in ${SKILLS}; do
    diff -r "${tmp}/${n}" "${DEST}/${n}" > /dev/null 2>&1 || stale="${stale}${n} "
  done
  if [ -n "${stale}" ]; then
    echo "stale stubs: ${stale% }"
    echo "the source under ${SRC} moved on - run: bash .devkit/stubs.sh"
    exit 1
  fi
  echo "stubs match ${SRC}"
  exit 0
fi

generate "${DEST}"
for n in ${SKILLS}; do echo "  written   ${DEST}/${n}"; done
