#!/usr/bin/env bash
# Shim. The real script is project/core/skills/commit-message/collect.sh, which is where it is
# maintained; it resolves the repository root itself, so this adds nothing but
# the path the skill instructions expect.
#
# Generated by .devkit/stubs.sh - do not edit.
exec bash "$(git rev-parse --show-toplevel)/project/core/skills/commit-message/collect.sh" "$@"
